image: java:8-jdk

stages:
  - build
  - production

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

production:
  type: deploy
  script:
  - ./gradlew clean build
  - dpl --provider=heroku --app=rara-education-demo --api-key=$58f17298-1974-4c71-abbd-0fa6ebfb75ce
  artifacts:
    paths:
      - backend/build/libs/backend.jar
  only:
  - master

after_script:
  - echo "End CI"